version: "3.9"
services:
  code-server:
    container_name: msb_code-server
    hostname: code-server
    image: ghcr.io/linuxserver/code-server:latest
      #https://hub.docker.com/r/linuxserver/code-server
    environment:
      - TZ=$TZ
      - PUID=$ID
      - PGID=$ID
    ports:
      - $SRV_IP_1:$CS_H_PORT:8443
    volumes:
       - $CS_CONFIG_DIR:/config
       - $ROOT_DIR:/app
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1g
  tftp:
    container_name: msb_tftp
    hostname: tftp
    build:
      context: ./app/tftp
    volumes:
      - $TFTP_LOG_DIR:/var/log
      - $TFTP_DATA_DIR:/srv/tftp
    ports:
      - $SRV_IP_1:69:69/udp
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512m
  ntp-a:
    container_name: msb_ntp-a
    hostname: ntp-a
    build:
      context: ./app/ntp
    ports:
      - $SRV_IP_1:123:123/udp
    cap_add:
      - SYS_TIME
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256m
  ntp-b:
    container_name: msb_ntp-b
    hostname: ntp-b
    build:
      context: ./app/ntp
    ports:
      - $SRV_IP_2:123:123/udp
    cap_add:
      - SYS_TIME
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256m
  elastic:
    container_name: msb_elastic
    hostname: elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
      #https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
        #set no more than half of allocated memory
        #https://www.elastic.co/guide/en/elasticsearch/reference/current/advanced-configuration.html#set-jvm-options
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - $ELASTIC_DATA_DIR:/usr/share/elasticsearch/data
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 8g
  logstash:
    depends_on:
      - elastic
    container_name: msb_logstash
    hostname: logstash
    build:
      context: ./app/elk/logstash
    volumes:
      - ${LOGSTASH_DATA_DIR}:/usr/share/logstash/data
    ports:
      - $SRV_IP_1:$LOGSTASH_H_PORT:$LOGSTASH_C_PORT/udp
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 3g
  kibana:
    depends_on:
      - elastic
    container_name: msb_kibana
    hostname: kibana
    build:
      context: ./app/kibana
    ports:
      - $SRV_IP_1:5601:5601
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2g