version: "3.9"
services:
  code-server:
    hostname: code-server
    image: ghcr.io/linuxserver/code-server:latest
      #https://hub.docker.com/r/linuxserver/code-server
    environment:
      - TZ=$TZ
      - PUID=$ID
      - PGID=$ID
    ports:
      - $SRV_IP_1:$CS_H_PORT:8443
    volumes:
       - $CS_CONFIG_DIR:/config
       - $ROOT_DIR:/app
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1g
  tftp:
    hostname: tftp
    build:
      context: ./app/tftp
    volumes:
      - $TFTP_LOG_DIR:/var/log
      - $TFTP_DATA_DIR:/srv/tftp
    ports:
      - $SRV_IP_1:69:69/udp
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512m
  ntp-a:
    hostname: ntp-a
    build:
      context: ./app/ntp
    ports:
      - $SRV_IP_1:123:123/udp
    cap_add:
      - SYS_TIME
    deploy:
      resources:
        limits:
          memory: 256m
  ntp-b:
    hostname: ntp-b
    build:
      context: ./app/ntp
    ports:
      - $SRV_IP_2:123:123/udp
    cap_add:
      - SYS_TIME
    deploy:
      resources:
        limits:
          memory: 256m